require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4

# not preferred as this rule makes harder to move/add/remove items
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false

# change without benefit ( foobar == nil into foobar.nil?)
Style/NilComparison:
  Enabled: false

# single-quoted strings are worse as adding #{} requires changing ' back into "
Style/StringLiterals:
  Enabled: false

# explicit return make easier to avoid subtle bugs on changing function
Style/RedundantReturn:
  Enabled: false

# sometimes it is necessary to use UTF in comment (especially in cases where some special handling is necessary for nonASCII text) 
Style/AsciiComments:
  Enabled: false

# block comments are fine in my opinion
Style/BlockComments:
  Enabled: false

# overcomplicated syntax without benefit
Style/WordArray:
  Enabled: false

# it is likely to detect bugs, there is no point in masking them by running autocorrect
Lint/UnusedMethodArgument:
  AutoCorrect: False
Lint/UnusedBlockArgument:
  AutoCorrect: False

# see https://github.com/bbatsov/rubocop/issues/1747#issuecomment-223370141
# this auto-correct rule may break things and is not a clear improvement
Style/SpecialGlobalVars:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

# Uncomment following rules to allow using tabs:
#Layout/Tab:
#  Enabled: false

#Layout/IndentationConsistency:
#  Enabled: false

#Layout/IndentationWidth:
#  Enabled: false
