require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4

# not preferred as this rule makes harder to move/add/remove items
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false

# change without benefit ( foobar == nil into foobar.nil?)
Style/NilComparison:
  Enabled: false

# single-quoted strings are worse as adding #{} requires changing ' back into "
Style/StringLiterals:
  Enabled: false

# explicit return make easier to avoid subtle bugs on changing function
Style/RedundantReturn:
  Enabled: false

# sometimes it is necessary to use UTF in comment (especially in cases where some special handling is necessary for nonASCII text) 
Style/AsciiComments:
  Enabled: false

# block comments are fine in my opinion
Style/BlockComments:
  Enabled: false

# overcomplicated syntax without benefit
Style/WordArray:
  Enabled: false

# it is likely to detect bugs, there is no point in masking them by running autocorrect
Lint/UnusedMethodArgument:
  AutoCorrect: False
Lint/UnusedBlockArgument:
  AutoCorrect: False

# see https://github.com/bbatsov/rubocop/issues/1747#issuecomment-223370141
# this auto-correct rule may break things and is not a clear improvement
Style/SpecialGlobalVars:
  Enabled: false

# there is no benefit from ugly code of collapsed form
Style/EmptyMethod:
  EnforcedStyle: expanded

# proposed changed code is ugly as hell
# if there is real performance benefit without ugly side-effects
# it should be fixed at language level
# potential investigation should start from
# https://github.com/rubocop-hq/rubocop/commit/864531f61634354570a6b4458cb599c4373659b7
Performance/RegexpMatch:
  Enabled: false

# unconvinced that it is useful
Style/RaiseArgs:
  Enabled: false

# Ruby-specific syntax has no benefits whatsover over slashes
# if there is one let me know
Style/RegexpLiteral:
  EnforcedStyle: slashes

# Standard array is much better and less overcomplicated
Style/SymbolArray:
  EnforcedStyle: brackets

# Neither is much better, consistency is much more important
# for example see:
# group = ["#{fish[0]}", "#{fish[0]} filet", "filet z #{fish[1]}"]
# group = [(fish[0]).to_s, "#{fish[0]} filet", "filet z #{fish[1]}"]
Style/UnneededInterpolation:
  Enabled: false

# local style optmization is better than global consistency
Style/StringLiteralsInInterpolation:
  Enabled: false

# this rubyism is not more readable
Style/NumericPredicate:
  Enabled: false

# Uncomment following rules to allow using tabs:
#Layout/Tab:
#  Enabled: false

#Layout/IndentationConsistency:
#  Enabled: false

#Layout/IndentationWidth:
#  Enabled: false
